### ISSUE TITLE
Can't get paginate to work correctly.

### ISSUE THREAD

**Issue by alee046** [alee046/projectTwo#2]
https://i.imgur.com/fSNSXFB.jpg

1. Users can see a live feed of other posts.
2. all the posts are floated so it looks weird. I cant seem to get the paginate gem to work properly.
3. https://i.imgur.com/oai71Di.png

**Comment by tambling** [comment]
This isn’t a Ruby/Rails issue– something in your CSS is wrong. As for the paginate gem, it looks like you’re not even mentioning it in `posts#index`, so of course it wouldn’t be paginating.

**Comment by h4w5** [comment]
I'm closing. If you need support, [follow the guidelines](https://github.com/ga-students/WDI_DTLA_6/tree/master/projects/project_issues_protocol) and resubmit.

Good luck!
